dotenv: .env
dependencies:
    - aave/protocol-v2@1.0.1
compiler:
    solc:
        remappings:  
            - "@aave=aave/protocol-v2@1.0.1"
wallets:
    from_key: ${PRIVATE_KEY}

networks:
    default: kovan
    kovan:
        weth_token: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
        lending_pool_addresses_provider: "0x88757f2f99175387ab4c6a4b3067c77a695b0349"
    mainnet-fork:
        lending_pool_addresses_provider: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
        weth_token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
        dai_addr: "0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa"
settings:
    gas_limit: 10000000